title: Arash Hatami
email: info@arash-hatami.ir
description: >-
  DevOps | Backend Developer
baseurl: ""
url: "https://portfolio.arash-hatami.ir"
repository: hatamiarash7/MyWebSite_Portfolio
twitter_username: hatamiarash7
github_username: hatamiarash7

plugins:
  - jekyll-sitemap

nav_exclude:
  - pages/404.html
  - pages/index.md

author:
  name: Arash Hatami
  image: assets/img/profile.jpg
  email: info@arash-hatami.ir
  instagram: hatamiarash7
  linkedin: hatamiarash7
  twitter: hatamiarash7
  facebook: hatamiarash7
  github: hatamiarash7
  gitlab: hatamiarash7
  keybase: hatamiarash7
  stackoverflow: 4905220

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name

analytics:
  enabled: true
  google:
    tracking_id: G-GDJJDL2D5F

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
