title: Arash Hatami
email: info@arash-hatami.ir
description: >-
  DevOps | Backend Developer
baseurl: ""
url: "https://portfolio.arash-hatami.ir"
repository: hatamiarash7/MyWebSite_Portfolio
twitter_username: hatamiarash7
github_username: hatamiarash7

#plugins:
#  - jemoji

nav_exclude:
  - pages/404.html
  - pages/index.md

author:
  name: Arash Hatami
  image: assets/img/profile.jpg
  email: info@arash-hatami.ir
  linkedin: hatamiarash7
  github: hatamiarash7
  gitlab: hatamiarash7
  instagram: hatamiarash7
  twitter: hatamiarash7
  facebook: hatamiarash7

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name

disqus:
  shortname: your-short-name-disqus

analytics:
  enabled: true
  google:
    tracking_id: your-google-tracking-id

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
